Create drug info script and url dictionary for patientslikeme.com
enTECHCC/enHealth pull request #2
Opened 2017-03-15 01:16 UTC by svillah

- [ ]  @M-Grab 

- [ ]  @SeanSiow 

drugInformation.py pulls drug information for a specific drug URL and exports to drugData.json 
drugsDict.py creates a dictionary that stores key: name of drug and value: URL for that drug

note: drugInformation.py may need to be updated when database is created

2017-03-22 00:21 UTC, M-Grab requested changes
Good job, just some clean up required :)

2017-03-22 00:21 UTC, M-Grab commented on patientslikeme/drugInformation.py
> +    print category
This is a debugging line, right? We probably don't want to be printing stuff to console live

2017-03-22 00:21 UTC, M-Grab commented on patientslikeme/drugInformation.py
> +    json.dump(data, f, indent=4)
magic number; use named constant?

2017-03-22 00:21 UTC, M-Grab commented on patientslikeme/drugsDict.py
> +allCat = [1,2]
magic numbers? Not sure what this variable is

2017-03-22 00:21 UTC, M-Grab commented on patientslikeme/drugsDict.py
> +                for drugUrl in drugs[i].findChildren("a"):
Looks like the same code block as in line 47. Try to abstract the logic to another function?

2017-03-22 00:21 UTC, M-Grab commented on patientslikeme/drugInformation.py
> +website = "https://www.patientslikeme.com/treatments/browse?cat=1"
This line down seems like old code. Is it still relevant here or is stuff handled in `drugDic.py`?

2017-03-22 01:46 UTC, svillah commented on patientslikeme/drugInformation.py
> +    print category
yes. reviewed & fixed!

2017-03-29 00:37 UTC, SeanSiow commented on patientslikeme/drugsDict.py
> +allCat = [1,2]
okay I gave fixed the issue by creating constants of each category and assigning them with the appropriate numbers

https://gyazo.com/00587a63888c70aeb0339c04b77a89c3

2017-03-29 00:37 UTC, SeanSiow commented on patientslikeme/drugsDict.py
> +                for drugUrl in drugs[i].findChildren("a"):
abstract function created

2017-03-29 00:40 UTC, M-Grab approved these changes

2017-03-29 00:40 UTC, merged